version: '3'

services:
 mysql:
  image: mysql:latest
  environment:
   MYSQL_ROOT_PASSWORD: mysql1337
 webapp:
  image: sebseib/nextcloud:latest
  ports:
   - 8082:80
  links:
   - mysql:mysql
  depends_on:
   - mysql
